/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./api/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Baker: { // root type
    address: string; // String!
    atRiskThreshold: number; // Int!
    blocksPerCycle: number; // Int!
    explorerUrl?: string | null; // String
    headDistance: number; // Int!
    lastProcessed?: NexusGenRootTypes['LastProcessed'] | null; // LastProcessed
    recentEvents: NexusGenRootTypes['LevelEvents'][]; // [LevelEvents!]!
    updatedAt: string; // String!
  }
  BakerEvent: { // root type
    kind: string; // String!
    priority?: number | null; // Int
    slotCount?: number | null; // Int
  }
  Bakers: { // root type
    items: NexusGenRootTypes['Baker'][]; // [Baker!]!
    totalCount: number; // Int!
  }
  BlockInfo: { // root type
    hash: string; // String!
    level: number; // Int!
    payload_round?: number | null; // Int
    priority?: number | null; // Int
    protocol: string; // String!
    timestamp: string; // String!
  }
  ConsensusKey: { // root type
    active: string; // String!
    explorerUrl?: string | null; // String
    pendings?: NexusGenRootTypes['PendingConsensusKey'][] | null; // [PendingConsensusKey!]
  }
  CpuData: { // root type
    brand: string; // String!
    cores: number; // Int!
    family: string; // String!
    manufacturer: string; // String!
    model: string; // String!
  }
  CpuTemperatureData: { // root type
    chipset?: number | null; // Float
    cores: Array<number | null>; // [Float]!
    main?: number | null; // Float
    max?: number | null; // Float
    socket?: Array<number | null> | null; // [Float]
  }
  CpuUsage: { // root type
    system?: number | null; // Float
    user?: number | null; // Float
  }
  CurrentLoadData: { // root type
    avgLoad: number; // Float!
  }
  FsSizeData: { // root type
    available: number; // Float!
    fs: string; // String!
    mount: string; // String!
    size: number; // Float!
    type: string; // String!
    use: number; // Float!
    used: number; // Float!
  }
  LastProcessed: { // root type
    cycle: number; // Int!
    cyclePosition: number; // Int!
    level: number; // Int!
  }
  LevelEvents: { // root type
    cycle: number; // Int!
    events: NexusGenRootTypes['BakerEvent'][]; // [BakerEvent!]!
    explorerUrl?: string | null; // String
    level: number; // Int!
    timestamp: string; // String!
  }
  MemData: { // root type
    active: number; // Float!
    swaptotal: number; // Float!
    swapused: number; // Float!
    total: number; // Float!
    used: number; // Float!
  }
  NetworkInfo: { // root type
    blocksPerCycle: number; // Int!
    cycle: number; // Int!
    cyclePosition: number; // Int!
    level: number; // Int!
    protocol: string; // String!
  }
  Nodes: { // root type
    items: NexusGenRootTypes['TezosNode'][]; // [TezosNode!]!
  }
  OsData: { // root type
    arch?: string | null; // String
    build?: string | null; // String
    codename?: string | null; // String
    codepage?: string | null; // String
    distro?: string | null; // String
    fqdn?: string | null; // String
    hostname?: string | null; // String
    hypervizor?: boolean | null; // Boolean
    kernel?: string | null; // String
    platform?: string | null; // String
    release?: string | null; // String
    servicepack?: string | null; // String
  }
  Participation: { // root type
    expected_cycle_activity: number; // Int!
    expected_endorsing_rewards: string; // String!
    minimal_cycle_activity: number; // Int!
    missed_levels: number; // Int!
    missed_slots: number; // Int!
    remaining_allowed_missed_slots: number; // Int!
  }
  PendingConsensusKey: { // root type
    cycle: number; // Int!
    pkh: string; // String!
  }
  ProcessInfo: { // root type
    command: string; // String!
    cpu: number; // Float!
    mem: number; // Float!
    memRss: number; // Float!
    memVsz: number; // Float!
    name: string; // String!
    params?: string | null; // String
    path?: string | null; // String
    pid: number; // Int!
    started: string; // String!
    user: string; // String!
  }
  PyrometerInfo: {};
  Query: {};
  Settings: { // root type
    showSystemInfo: boolean; // Boolean!
  }
  SysInfo: { // root type
    cpu: NexusGenRootTypes['CpuData']; // CpuData!
    cpuTemperature: NexusGenRootTypes['CpuTemperatureData']; // CpuTemperatureData!
    currentLoad: NexusGenRootTypes['CurrentLoadData']; // CurrentLoadData!
    fullLoad: number; // Float!
    mem: NexusGenRootTypes['MemData']; // MemData!
  }
  TezosNode: { // root type
    bootstrapped?: boolean | null; // Boolean
    error?: string | null; // String
    name: string; // String!
    peerCount?: number | null; // Int
    recentBlocks: NexusGenRootTypes['BlockInfo'][]; // [BlockInfo!]!
    synced?: string | null; // String
    tezosVersion: NexusGenRootTypes['TezosVersion']; // TezosVersion!
    unableToReach?: boolean | null; // Boolean
    updatedAt: string; // String!
    url: string; // String!
  }
  TezosVersion: { // root type
    chainName: string; // String!
    commitHash: string; // String!
    version: string; // String!
  }
  TzAddressAlias: { // root type
    address: string; // String!
    alias: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Baker: { // field return type
    address: string; // String!
    atRisk: boolean | null; // Boolean
    atRiskThreshold: number; // Int!
    balance: string | null; // String
    blocksPerCycle: number; // Int!
    consensusKey: NexusGenRootTypes['ConsensusKey'] | null; // ConsensusKey
    deactivated: boolean | null; // Boolean
    explorerUrl: string | null; // String
    frozenBalance: string | null; // String
    gracePeriod: number | null; // Int
    headDistance: number; // Int!
    lastProcessed: NexusGenRootTypes['LastProcessed'] | null; // LastProcessed
    participation: NexusGenRootTypes['Participation'] | null; // Participation
    recentEvents: NexusGenRootTypes['LevelEvents'][]; // [LevelEvents!]!
    stakingBalance: string | null; // String
    updatedAt: string; // String!
  }
  BakerEvent: { // field return type
    kind: string; // String!
    priority: number | null; // Int
    slotCount: number | null; // Int
  }
  Bakers: { // field return type
    items: NexusGenRootTypes['Baker'][]; // [Baker!]!
    totalCount: number; // Int!
  }
  BlockInfo: { // field return type
    hash: string; // String!
    level: number; // Int!
    payloadRound: number | null; // Int
    payload_round: number | null; // Int
    priority: number | null; // Int
    protocol: string; // String!
    timestamp: string; // String!
  }
  ConsensusKey: { // field return type
    active: string; // String!
    explorerUrl: string | null; // String
    pendings: NexusGenRootTypes['PendingConsensusKey'][] | null; // [PendingConsensusKey!]
  }
  CpuData: { // field return type
    brand: string; // String!
    cores: number; // Int!
    family: string; // String!
    manufacturer: string; // String!
    model: string; // String!
  }
  CpuTemperatureData: { // field return type
    chipset: number | null; // Float
    cores: Array<number | null>; // [Float]!
    main: number | null; // Float
    max: number | null; // Float
    socket: Array<number | null> | null; // [Float]
  }
  CpuUsage: { // field return type
    system: number | null; // Float
    user: number | null; // Float
  }
  CurrentLoadData: { // field return type
    avgLoad: number; // Float!
  }
  FsSizeData: { // field return type
    available: number; // Float!
    fs: string; // String!
    mount: string; // String!
    size: number; // Float!
    type: string; // String!
    use: number; // Float!
    used: number; // Float!
  }
  LastProcessed: { // field return type
    cycle: number; // Int!
    cyclePosition: number; // Int!
    level: number; // Int!
  }
  LevelEvents: { // field return type
    cycle: number; // Int!
    events: NexusGenRootTypes['BakerEvent'][]; // [BakerEvent!]!
    explorerUrl: string | null; // String
    level: number; // Int!
    timestamp: string; // String!
  }
  MemData: { // field return type
    active: number; // Float!
    swaptotal: number; // Float!
    swapused: number; // Float!
    total: number; // Float!
    used: number; // Float!
  }
  NetworkInfo: { // field return type
    blocksPerCycle: number; // Int!
    chainName: string; // String!
    cycle: number; // Int!
    cyclePosition: number; // Int!
    level: number; // Int!
    protocol: string; // String!
  }
  Nodes: { // field return type
    items: NexusGenRootTypes['TezosNode'][]; // [TezosNode!]!
    totalCount: number; // Int!
  }
  OsData: { // field return type
    arch: string | null; // String
    build: string | null; // String
    codename: string | null; // String
    codepage: string | null; // String
    distro: string | null; // String
    fqdn: string | null; // String
    hostname: string | null; // String
    hypervizor: boolean | null; // Boolean
    kernel: string | null; // String
    platform: string | null; // String
    release: string | null; // String
    servicepack: string | null; // String
  }
  Participation: { // field return type
    expected_cycle_activity: number; // Int!
    expected_endorsing_rewards: string; // String!
    minimal_cycle_activity: number; // Int!
    missed_levels: number; // Int!
    missed_slots: number; // Int!
    remaining_allowed_missed_slots: number; // Int!
  }
  PendingConsensusKey: { // field return type
    cycle: number; // Int!
    pkh: string; // String!
  }
  ProcessInfo: { // field return type
    command: string; // String!
    cpu: number; // Float!
    mem: number; // Float!
    memRss: number; // Float!
    memVsz: number; // Float!
    name: string; // String!
    params: string | null; // String
    path: string | null; // String
    pid: number; // Int!
    started: string; // String!
    user: string; // String!
  }
  PyrometerInfo: { // field return type
    processes: NexusGenRootTypes['ProcessInfo'][]; // [ProcessInfo!]!
    version: string; // String!
  }
  Query: { // field return type
    aliases: NexusGenRootTypes['TzAddressAlias'][]; // [TzAddressAlias!]!
    bakers: NexusGenRootTypes['Bakers']; // Bakers!
    networkInfo: NexusGenRootTypes['NetworkInfo'] | null; // NetworkInfo
    nodes: NexusGenRootTypes['Nodes']; // Nodes!
    pyrometer: NexusGenRootTypes['PyrometerInfo']; // PyrometerInfo!
    settings: NexusGenRootTypes['Settings']; // Settings!
    sysInfo: NexusGenRootTypes['SysInfo']; // SysInfo!
  }
  Settings: { // field return type
    showSystemInfo: boolean; // Boolean!
  }
  SysInfo: { // field return type
    cpu: NexusGenRootTypes['CpuData']; // CpuData!
    cpuTemperature: NexusGenRootTypes['CpuTemperatureData']; // CpuTemperatureData!
    currentLoad: NexusGenRootTypes['CurrentLoadData']; // CurrentLoadData!
    fsSize: Array<NexusGenRootTypes['FsSizeData'] | null>; // [FsSizeData]!
    fullLoad: number; // Float!
    inetLatency: number; // Float!
    mem: NexusGenRootTypes['MemData']; // MemData!
    osInfo: NexusGenRootTypes['OsData']; // OsData!
  }
  TezosNode: { // field return type
    bootstrapped: boolean | null; // Boolean
    error: string | null; // String
    name: string; // String!
    peerCount: number | null; // Int
    recentBlocks: NexusGenRootTypes['BlockInfo'][]; // [BlockInfo!]!
    synced: string | null; // String
    tezosVersion: NexusGenRootTypes['TezosVersion']; // TezosVersion!
    unableToReach: boolean | null; // Boolean
    updatedAt: string; // String!
    url: string; // String!
  }
  TezosVersion: { // field return type
    chainName: string; // String!
    commitHash: string; // String!
    version: string; // String!
  }
  TzAddressAlias: { // field return type
    address: string; // String!
    alias: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  Baker: { // field return type name
    address: 'String'
    atRisk: 'Boolean'
    atRiskThreshold: 'Int'
    balance: 'String'
    blocksPerCycle: 'Int'
    consensusKey: 'ConsensusKey'
    deactivated: 'Boolean'
    explorerUrl: 'String'
    frozenBalance: 'String'
    gracePeriod: 'Int'
    headDistance: 'Int'
    lastProcessed: 'LastProcessed'
    participation: 'Participation'
    recentEvents: 'LevelEvents'
    stakingBalance: 'String'
    updatedAt: 'String'
  }
  BakerEvent: { // field return type name
    kind: 'String'
    priority: 'Int'
    slotCount: 'Int'
  }
  Bakers: { // field return type name
    items: 'Baker'
    totalCount: 'Int'
  }
  BlockInfo: { // field return type name
    hash: 'String'
    level: 'Int'
    payloadRound: 'Int'
    payload_round: 'Int'
    priority: 'Int'
    protocol: 'String'
    timestamp: 'String'
  }
  ConsensusKey: { // field return type name
    active: 'String'
    explorerUrl: 'String'
    pendings: 'PendingConsensusKey'
  }
  CpuData: { // field return type name
    brand: 'String'
    cores: 'Int'
    family: 'String'
    manufacturer: 'String'
    model: 'String'
  }
  CpuTemperatureData: { // field return type name
    chipset: 'Float'
    cores: 'Float'
    main: 'Float'
    max: 'Float'
    socket: 'Float'
  }
  CpuUsage: { // field return type name
    system: 'Float'
    user: 'Float'
  }
  CurrentLoadData: { // field return type name
    avgLoad: 'Float'
  }
  FsSizeData: { // field return type name
    available: 'Float'
    fs: 'String'
    mount: 'String'
    size: 'Float'
    type: 'String'
    use: 'Float'
    used: 'Float'
  }
  LastProcessed: { // field return type name
    cycle: 'Int'
    cyclePosition: 'Int'
    level: 'Int'
  }
  LevelEvents: { // field return type name
    cycle: 'Int'
    events: 'BakerEvent'
    explorerUrl: 'String'
    level: 'Int'
    timestamp: 'String'
  }
  MemData: { // field return type name
    active: 'Float'
    swaptotal: 'Float'
    swapused: 'Float'
    total: 'Float'
    used: 'Float'
  }
  NetworkInfo: { // field return type name
    blocksPerCycle: 'Int'
    chainName: 'String'
    cycle: 'Int'
    cyclePosition: 'Int'
    level: 'Int'
    protocol: 'String'
  }
  Nodes: { // field return type name
    items: 'TezosNode'
    totalCount: 'Int'
  }
  OsData: { // field return type name
    arch: 'String'
    build: 'String'
    codename: 'String'
    codepage: 'String'
    distro: 'String'
    fqdn: 'String'
    hostname: 'String'
    hypervizor: 'Boolean'
    kernel: 'String'
    platform: 'String'
    release: 'String'
    servicepack: 'String'
  }
  Participation: { // field return type name
    expected_cycle_activity: 'Int'
    expected_endorsing_rewards: 'String'
    minimal_cycle_activity: 'Int'
    missed_levels: 'Int'
    missed_slots: 'Int'
    remaining_allowed_missed_slots: 'Int'
  }
  PendingConsensusKey: { // field return type name
    cycle: 'Int'
    pkh: 'String'
  }
  ProcessInfo: { // field return type name
    command: 'String'
    cpu: 'Float'
    mem: 'Float'
    memRss: 'Float'
    memVsz: 'Float'
    name: 'String'
    params: 'String'
    path: 'String'
    pid: 'Int'
    started: 'String'
    user: 'String'
  }
  PyrometerInfo: { // field return type name
    processes: 'ProcessInfo'
    version: 'String'
  }
  Query: { // field return type name
    aliases: 'TzAddressAlias'
    bakers: 'Bakers'
    networkInfo: 'NetworkInfo'
    nodes: 'Nodes'
    pyrometer: 'PyrometerInfo'
    settings: 'Settings'
    sysInfo: 'SysInfo'
  }
  Settings: { // field return type name
    showSystemInfo: 'Boolean'
  }
  SysInfo: { // field return type name
    cpu: 'CpuData'
    cpuTemperature: 'CpuTemperatureData'
    currentLoad: 'CurrentLoadData'
    fsSize: 'FsSizeData'
    fullLoad: 'Float'
    inetLatency: 'Float'
    mem: 'MemData'
    osInfo: 'OsData'
  }
  TezosNode: { // field return type name
    bootstrapped: 'Boolean'
    error: 'String'
    name: 'String'
    peerCount: 'Int'
    recentBlocks: 'BlockInfo'
    synced: 'String'
    tezosVersion: 'TezosVersion'
    unableToReach: 'Boolean'
    updatedAt: 'String'
    url: 'String'
  }
  TezosVersion: { // field return type name
    chainName: 'String'
    commitHash: 'String'
    version: 'String'
  }
  TzAddressAlias: { // field return type name
    address: 'String'
    alias: 'String'
  }
}

export interface NexusGenArgTypes {
  Query: {
    bakers: { // args
      bakers?: string[] | null; // [String!]
      limit: number; // Int!
      offset: number; // Int!
    }
    nodes: { // args
      limit: number; // Int!
      offset: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}